# whole project docker compose

version: '3.9'

services:
  server:
    build: ./server
    container_name: twitter-nginx
    restart: on-failure
    env_file: .env
    depends_on:
      api:
        condition: service_started
    networks:
      - twitter
    ports:
      - "80:5000"
    volumes:
      - ./server/static:/usr/share/nginx/html/

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    env_file: .env
    container_name: twitter-api
    networks:
      - twitter
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
    entrypoint:
      sh -c "
      alembic upgrade head &&
      uvicorn main:app --reload
      "

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    networks:
      - twitter
    restart: on-failure
    env_file: .env
    container_name: twitter-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./src/database/pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
  migrations:
  src:
  pgadmin:

networks:
  twitter:
    driver: bridge


# TODO redis, celery, EFK, Prometheus-Grafana