version: '3.9'
services:
  postgres:
    image: postgres:15.2
    container_name: postgres-local
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGUSER=admin
    ports:
      - '5432:5432'